"""table modificate

Revision ID: 19fe8cf786fd
Revises: 368158397465
Create Date: 2025-05-25 21:40:18.025611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fe8cf786fd'
down_revision = '368158397465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
